// <auto-generated />
namespace WordPlay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Resolve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resolve));
        
        string IMigrationMetadata.Id
        {
            get { return "201509240649232_Resolve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
