// <auto-generated />
namespace WordPlay.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class updatet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatet));
        
        string IMigrationMetadata.Id
        {
            get { return "201509241252550_updatet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
